name       : sloccount
version    : 2.26
release    : 1
source     :
    - http://tenet.dl.sourceforge.net/project/sloccount/sloccount-2.26.tar.gz : fa7fa2bbf2f627dd2d0fdb958bd8ec4527231254c120a8b4322405d8a4e3d12b
license    : GPL-2.0
component  : programming.tools
summary    : SLOCCount, a set of the programs for counting source lines of code (SLOC)
description: |
    SLOCCount, a set of the programs for counting source lines of code (SLOC)
build      : |
    %make
install    : |
    install -d -m 00644 $installdir/usr/bin
    %make_install PREFIX=$installdir/usr
